# Generated by Django 4.0.4 on 2022-05-07 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='リーグカテゴリ')),
                ('players', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='参加者')),
            ],
        ),
        migrations.CreateModel(
            name='ResultTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp', models.IntegerField(verbose_name='dp')),
                ('win', models.IntegerField(verbose_name='勝ち数')),
                ('loose', models.IntegerField(verbose_name='負け数')),
                ('game_num', models.IntegerField(verbose_name='試合数')),
                ('league_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_table', to='game.leaguecategory', verbose_name='リーグカテゴリ')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_table', to=settings.AUTH_USER_MODEL, verbose_name='player')),
            ],
        ),
    ]
