# Generated by Django 4.0.4 on 2022-05-07 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_rename_league_category_resulttable_league_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resulttable',
            name='dp',
            field=models.IntegerField(blank=True, default=0, verbose_name='dp'),
        ),
        migrations.AlterField(
            model_name='resulttable',
            name='game_num',
            field=models.IntegerField(blank=True, default=0, verbose_name='試合数'),
        ),
        migrations.AlterField(
            model_name='resulttable',
            name='loose',
            field=models.IntegerField(blank=True, default=0, verbose_name='負け数'),
        ),
        migrations.AlterField(
            model_name='resulttable',
            name='player',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_table', to=settings.AUTH_USER_MODEL, verbose_name='player'),
        ),
        migrations.AlterField(
            model_name='resulttable',
            name='win',
            field=models.IntegerField(blank=True, default=0, verbose_name='勝ち数'),
        ),
    ]
