# Generated by Django 4.0.4 on 2022-05-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_resulttable_dp_alter_resulttable_game_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resulttable',
            name='dp',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='dp'),
        ),
        migrations.AlterField(
            model_name='resulttable',
            name='game_num',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='試合数'),
        ),
        migrations.AlterField(
            model_name='resulttable',
            name='loose',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='負け数'),
        ),
        migrations.AlterField(
            model_name='resulttable',
            name='win',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='勝ち数'),
        ),
    ]
