# Generated by Django 4.0.4 on 2022-05-07 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0004_alter_resulttable_dp_alter_resulttable_game_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resulttable',
            name='dp',
            field=models.PositiveIntegerField(default=0, verbose_name='dp'),
        ),
        migrations.AlterField(
            model_name='resulttable',
            name='game_num',
            field=models.PositiveIntegerField(default=0, verbose_name='試合数'),
        ),
        migrations.AlterField(
            model_name='resulttable',
            name='loose',
            field=models.PositiveIntegerField(default=0, verbose_name='負け数'),
        ),
        migrations.AlterField(
            model_name='resulttable',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_table', to=settings.AUTH_USER_MODEL, verbose_name='player'),
        ),
        migrations.AlterField(
            model_name='resulttable',
            name='win',
            field=models.PositiveIntegerField(default=0, verbose_name='勝ち数'),
        ),
        migrations.CreateModel(
            name='WaitingPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_player', to='game.leaguecategory', verbose_name='リーグカテゴリ')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_player', to=settings.AUTH_USER_MODEL, verbose_name='player')),
            ],
        ),
    ]
