# Generated by Django 4.0.4 on 2022-05-07 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import game.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0005_alter_resulttable_dp_alter_resulttable_game_num_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('room', models.CharField(max_length=200, verbose_name='room名')),
                ('result', models.JSONField(default=game.models.default_result, verbose_name='試合結果')),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始日時')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_player1', to=settings.AUTH_USER_MODEL, verbose_name='player1')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_player2', to=settings.AUTH_USER_MODEL, verbose_name='player2')),
            ],
        ),
    ]
