# Generated by Django 4.0.4 on 2022-05-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitingplayer',
            name='dp',
            field=models.PositiveIntegerField(default=0, verbose_name='dp'),
        ),
    ]
