# Generated by Django 4.0.4 on 2022-05-08 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0007_waitingplayer_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='room',
            field=models.CharField(max_length=200, unique=True, verbose_name='room名'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200, verbose_name='チャットメッセージ')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_message', to='game.game', verbose_name='試合')),
                ('postted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_message', to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
        ),
    ]
