# Generated by Django 4.0.4 on 2022-05-08 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_rename_postted_by_chatmessage_posted_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='text',
            new_name='content',
        ),
    ]
