# Generated by Django 4.0.4 on 2022-05-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_rename_text_chatmessage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguecategory',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='リーグカテゴリ'),
        ),
    ]
