# Generated by Django 4.0.4 on 2022-05-08 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_leaguecategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='game.leaguecategory', verbose_name='リーグカテゴリ'),
        ),
    ]
