# Generated by Django 4.0.4 on 2022-05-08 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_alter_game_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='game.leaguecategory', verbose_name='リーグカテゴリ'),
        ),
    ]
