# Generated by Django 4.0.4 on 2022-05-08 09:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0014_alter_game_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='submitted_players',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='結果提出者'),
        ),
    ]
