# Generated by Django 4.0.4 on 2022-05-09 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_alter_leaguecategory_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguecategory',
            name='finish_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='終了日時'),
        ),
        migrations.AddField(
            model_name='leaguecategory',
            name='start_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始日時'),
        ),
    ]
