# Generated by Django 4.0.4 on 2022-05-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_leaguecategory_finish_at_leaguecategory_start_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='resulttable',
            name='rank',
            field=models.PositiveIntegerField(default=1, verbose_name='順位'),
        ),
    ]
