# Generated by Django 4.0.4 on 2022-05-10 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_resulttable_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguecategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='leaguecategory',
            name='finish_at',
            field=models.DateTimeField(verbose_name='終了日時'),
        ),
        migrations.AlterField(
            model_name='leaguecategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='リーグカテゴリ'),
        ),
        migrations.AlterField(
            model_name='leaguecategory',
            name='start_at',
            field=models.DateTimeField(verbose_name='開始日時'),
        ),
    ]
