# Generated by Django 4.0.4 on 2022-05-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_leaguecategory_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguecategory',
            name='participants',
            field=models.IntegerField(default=0, verbose_name='参加人数'),
        ),
    ]
