# Generated by Django 4.0.4 on 2022-05-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_leaguecategory_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='win_rate12',
            field=models.DecimalField(decimal_places=10, default=0.5, max_digits=11),
        ),
        migrations.AddField(
            model_name='game',
            name='win_rate21',
            field=models.DecimalField(decimal_places=10, default=0.5, max_digits=11),
        ),
        migrations.AlterField(
            model_name='resulttable',
            name='dp',
            field=models.PositiveIntegerField(default=1500, verbose_name='dp'),
        ),
    ]
