# Generated by Django 4.0.4 on 2022-05-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_game_win_rate12_game_win_rate21_alter_resulttable_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resulttable',
            name='dp',
            field=models.FloatField(default=1500, verbose_name='dp'),
        ),
    ]
