# Generated by Django 4.0.4 on 2022-05-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_alter_resulttable_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resulttable',
            name='dp',
            field=models.DecimalField(decimal_places=1, default=1500, max_digits=5, verbose_name='dp'),
        ),
    ]
